apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: my-test-app
  ports:
    - port: 80              # External port
      targetPort: 80        # Container port
      nodePort: 30000
