kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: project2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: wiings09/passop-k8s-frontend:v1
          ports:
            - containerPort: 80