kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage 
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate    # Use "WaitForFirstConsumer" if using dynamic provisioning
reclaimPolicy: Retain
